# Disable the default trigger for pushes to branches
trigger: none

# Triggering on PRs for all branches is the default so specifying this isn't required
#pr:
#  branches:
#    include:
#    - '*'

stages:
- template: build-template.yml
  parameters:
    vmImage: 'vs2017-win2016'