trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md

pr: none

variables:
  azureSubscription: e0fbc786-67e5-421f-8d33-19cd6b7e246c
  functionAppName: AzureFunction-Pipelines
  vmImageName: 'vs2017-win2016'

stages:
  - template: templates/build-template.yml
    parameters:
      vmImage: ${{ variables.vmImageName }}
  - stage: Deploy
    displayName: Deploy stage
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: Deploy
        displayName: Deploy
        environment: development
        pool:
          vmImage: $(vmImageName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureFunctionApp@1
                  inputs:
                    azureSubscription: $(azureSubscription)
                    appType: functionApp
                    appName: $(functionAppName)
                    deployToSlotOrASE: true
                    resourceGroupName: AzureFunction2
                    slotName: stage
                    package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
                    deploymentMethod: auto
      - job: Approve
        displayName: Approve
        dependsOn: Deploy
        pool: server
        steps:
          - task: ManualValidation@0
            inputs:
              notifyUsers: adam.kadzban@relativity.com
              instructions: Hey go approve the deployment
              onTimeout: reject
      - template: templates/swap-template.yml
        parameters:
          vmImage: ${{ variables.vmImageName }}
          sourceSlot: 'stage'
          targetSlot: 'production'
          dependsOn: 'Approve'