# Disable the default trigger for pushes to branches
trigger: none

# Triggering on PRs for all branches is the default so specifying this isn't required
#pr:
#  branches:
#    include:
#    - '*'

resources:
  repositories:
    - repository: templates
      type: github
      name: adamkadzban/AzureFunction-Pipelines-Templates
      endpoint: adamkadzban

stages:
- template: build-template.yml@templates
  parameters:
    vmImage: 'vs2017-win2016'