# Don't ever run automatically
trigger: none
pr: none

parameters:
- name: sourceSlot
  type: string
  default: stage
- name: targetSlot
  type: string
  default: production
- name: stageToProduction
  type: boolean
  default: false

jobs:
- template: templates/swap-template.yml
  parameters:
    vmImage: 'vs2017-win2016'
    sourceSlot: ${{ parameters.sourceSlot }}
    targetSlot: ${{ parameters.targetSlot }}
    stageToProd: ${{ parameters.stageToProduction }}
    connection: 'e0fbc786-67e5-421f-8d33-19cd6b7e246c'