# Don't ever run automatically
trigger: none
pr: none

parameters:
- name: sourceSlot
  type: string
  default: stage
- name: targetSlot
  type: string
  default: production
- name: stageToProduction
  type: boolean
  default: false

resources:
  repositories:
    - repository: templates
      type: github
      name: adamkadzban/AzureFunction-Pipelines-Templates
      endpoint: adamkadzban

jobs:
- template: swap-template.yml@templates
  parameters:
    vmImage: 'vs2017-win2016'
    sourceSlot: ${{ parameters.sourceSlot }}
    targetSlot: ${{ parameters.targetSlot }}
    stageToProd: ${{ parameters.stageToProduction }}
    connection: 'e0fbc786-67e5-421f-8d33-19cd6b7e246c'