parameters:
- name: vmImage
  type: string
  default: 'vs2017-win2016'
  values:
  - 'windows-latest'
  - 'vs2017-win2016'

stages:
- stage: Build
  displayName: Build stage
  variables: 
    vmImage: ${{ parameters.vmImage }}

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImage)

    steps:
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: |
          $(System.DefaultWorkingDirectory)/**/*.sln
        arguments: --output $(System.DefaultWorkingDirectory)/publish_output --configuration Release

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop
